name: Build Mod
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make gradlew executable
        run: chmod +x ./gradlew || true
      - name: Build (skip tests)
        run: ./gradlew clean build -x test --no-daemon
      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: mod-jars
          path: build/libs/*.jar
